# Black Duck configuration
detect.excluded.directories=dev,node_modules,vendor,.git,.idea
detect.excluded.detector.types=NPM,YARN
detect.project.name=magento2-extension
detect.project.version.name=main
