#!/usr/bin/env bash

export PATH=/bin:/usr/local/bin:$PATH

cd /app

echo "-|| Setting base URL"
bin/magento config:set web/unsecure/base_url ${MAGENTO_URL}/

echo "-|| Install plugin..."
if [[ ! $(bin/magento module:status | grep Emartech_Emarsys) ]]
then
  echo "   >> Installing plugin"
  composer dump-autoload
  bin/magento setup:upgrade
else
  echo "   >> Skipping installation."
fi


bin/magento cache:flush