#!/usr/bin/env bash

export PATH=/bin:/usr/local/bin:$PATH

TABLE_PREFIX=$(mysql -sN -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e "SELECT SUBSTRING_INDEX(TABLE_NAME, 'core_config_data', 1) AS table_prefix FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE '%core_config_data' AND TABLE_SCHEMA = '$MYSQL_DATABASE';")
echo "The table prefix is: '$TABLE_PREFIX'"

cd /app

echo "-|| Setting base URL"
echo $MAGENTO_URL
bin/magento config:set web/unsecure/base_url ${MAGENTO_URL}/ \
|| mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e "update ${TABLE_PREFIX}core_config_data set value = '$MAGENTO_URL/' where path = 'web/unsecure/base_url';"

echo "-|| Install plugin..."
if [[ ! $(bin/magento module:status | grep Emartech_Emarsys) ]]
then
  echo "   >> Installing plugin"
  php /opt/emartech/composer-config.php ./composer.json add_local_plugin
  composer dump-autoload
  bin/magento setup:upgrade | grep -A 1 "Emartech"
else
  echo "   >> Skipping installation."
fi

mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e "UPDATE ${TABLE_PREFIX}oauth_token SET token = 'Almafa456';"

echo "-|| Flushing cache"
bin/magento cache:flush