<?php
/**
 * @category   Emarsys
 * @package    Emartech_Emarsys
 * @copyright  Copyright (c) 2019 Emarsys. (http://www.emarsys.net/)
 */
/** @var Emartech\Emarsys\Block\Success $block */
?>
<script>
    window.Emarsys = window.Emarsys || {};
    window.Emarsys.Magento2 = window.Emarsys.Magento2 || {};
    window.Emarsys.Magento2.orderData = <?= /* @noEscape */ $block->getOrderData() ?>;
</script>
