<?php
/**
 * @category   Emarsys
 * @package    Emartech_Emarsys
 * @copyright  Copyright (c) 2019 Emarsys. (http://www.emarsys.net/)
 */
/** @var Emartech\Emarsys\Block\Success $block */
?>
<script type="text/javascript">
    window.Emarsys = window.Emarsys || {};
    window.Emarsys.Magento2 = window.Emarsys.Magento2 || {};
    window.Emarsys.Magento2.orderData = <?php echo json_encode($block->getOrderData()); ?>;
</script>
