FROM registry.itg.cloud/itg-commerce/emarsys-magento2-extension-test/cypress:13.6.4
ARG NPM_TOKEN
ENV NPM_TOKEN=${NPM_TOKEN}

COPY testv2 /test

WORKDIR /test
RUN npm i
RUN ./node_modules/.bin/cypress install
# RUN ./node_modules/.bin/cypress verify && free

#CMD /usr/local/bin/shell.sh ; sleep infinity
