'use strict';

const customerAttributes = {
  old: [
    { code: 'confirmation', name: 'Is Confirmed' },
    { code: 'created_at', name: 'Created At' },
    { code: 'created_in', name: 'Created From' },
    { code: 'default_billing', name: 'Default Billing Address' },
    { code: 'default_shipping', name: 'Default Shipping Address' },
    { code: 'disable_auto_group_change', name: 'Disable Automatic Group Change Based on VAT ID' },
    { code: 'dob', name: 'Date of Birth' },
    { code: 'email', name: 'Email' },
    { code: 'emarsys_test_favorite_book', name: 'Favorite Book' },
    { code: 'emarsys_test_favorite_car', name: 'Favorite Car' },
    { code: 'emarsys_test_favorite_movie', name: 'Favorite Movie' },
    { code: 'emarsys_test_favorite_song', name: 'Favorite Song' },
    { code: 'emarsys_test_favorite_sport', name: 'Favorite Sport' },
    { code: 'failures_num', name: 'Failures Number' },
    { code: 'firstname', name: 'First Name' },
    { code: 'first_failure', name: 'First Failure Date' },
    { code: 'gender', name: 'Gender' },
    { code: 'group_id', name: 'Group' },
    { code: 'lastname', name: 'Last Name' },
    { code: 'lock_expires', name: 'Failures Number' },
    { code: 'middlename', name: 'Middle Name/Initial' },
    { code: 'prefix', name: 'Prefix' },
    { code: 'store_id', name: 'Create In' },
    { code: 'suffix', name: 'Suffix' },
    { code: 'taxvat', name: 'Tax/VAT Number' },
    { code: 'updated_at', name: 'Updated At' },
    { code: 'website_id', name: 'Associate to Website' }
  ],
  new: [
    { code: 'confirmation', name: 'Is Confirmed' },
    { code: 'created_at', name: 'Created At' },
    { code: 'created_in', name: 'Created From' },
    { code: 'default_billing', name: 'Default Billing Address' },
    { code: 'default_shipping', name: 'Default Shipping Address' },
    { code: 'disable_auto_group_change', name: 'Disable Automatic Group Change Based on VAT ID' },
    { code: 'dob', name: 'Date of Birth' },
    { code: 'email', name: 'Email' },
    { code: 'emarsys_test_favorite_book', name: 'Favorite Book' },
    { code: 'emarsys_test_favorite_car', name: 'Favorite Car' },
    { code: 'emarsys_test_favorite_movie', name: 'Favorite Movie' },
    { code: 'emarsys_test_favorite_song', name: 'Favorite Song' },
    { code: 'emarsys_test_favorite_sport', name: 'Favorite Sport' },
    { code: 'failures_num', name: 'Failures Number' },
    { code: 'firstname', name: 'First Name' },
    { code: 'first_failure', name: 'First Failure Date' },
    { code: 'gender', name: 'Gender' },
    { code: 'group_id', name: 'Group' },
    { code: 'lastname', name: 'Last Name' },
    { code: 'lock_expires', name: 'Failures Number' },
    { code: 'middlename', name: 'Middle Name/Initial' },
    { code: 'prefix', name: 'Name Prefix' },
    { code: 'store_id', name: 'Create In' },
    { code: 'suffix', name: 'Name Suffix' },
    { code: 'taxvat', name: 'Tax/VAT Number' },
    { code: 'updated_at', name: 'Updated At' },
    { code: 'website_id', name: 'Associate to Website' }
  ],
  enterprise: [
    { code: 'website_id', name: 'Associate to Website' },
    { code: 'store_id', name: 'Create In' },
    { code: 'created_in', name: 'Created From' },
    { code: 'prefix', name: 'Name Prefix' },
    { code: 'firstname', name: 'First Name' },
    { code: 'middlename', name: 'Middle Name/Initial' },
    { code: 'lastname', name: 'Last Name' },
    { code: 'suffix', name: 'Name Suffix' },
    { code: 'email', name: 'Email' },
    { code: 'group_id', name: 'Group' },
    { code: 'dob', name: 'Date of Birth' },
    { code: 'default_billing', name: 'Default Billing Address' },
    { code: 'default_shipping', name: 'Default Shipping Address' },
    { code: 'taxvat', name: 'Tax/VAT Number' },
    { code: 'confirmation', name: 'Is Confirmed' },
    { code: 'created_at', name: 'Created At' },
    { code: 'gender', name: 'Gender' },
    { code: 'disable_auto_group_change', name: 'Disable Automatic Group Change Based on VAT ID' },
    { code: 'updated_at', name: 'Updated At' },
    { code: 'failures_num', name: 'Failures Number' },
    { code: 'first_failure', name: 'First Failure Date' },
    { code: 'lock_expires', name: 'Failures Number' },
    { code: 'reward_update_notification', name: 'Reward update notification' },
    { code: 'reward_warning_notification', name: 'Reward warning notification' },
    { code: 'emarsys_test_favorite_sport', name: 'Favorite Sport' },
    { code: 'emarsys_test_favorite_book', name: 'Favorite Book' },
    { code: 'emarsys_test_favorite_movie', name: 'Favorite Movie' },
    { code: 'emarsys_test_favorite_song', name: 'Favorite Song' },
    { code: 'emarsys_test_favorite_car', name: 'Favorite Car' }
  ]
};

const customerAddressAttributes = {
  old: [
    { code: 'city', name: 'City' },
    { code: 'company', name: 'Company' },
    { code: 'country_id', name: 'Country' },
    { code: 'emarsys_test_building_type', name: 'Building Type' },
    { code: 'emarsys_test_door_bell', name: 'Door Bell' },
    { code: 'emarsys_test_floor', name: 'Floor' },
    { code: 'emarsys_test_type_of_residence', name: 'Type Of Residence' },
    { code: 'emarsys_test_type_of_street', name: 'Type Of Street' },
    { code: 'fax', name: 'Fax' },
    { code: 'firstname', name: 'First Name' },
    { code: 'lastname', name: 'Last Name' },
    { code: 'middlename', name: 'Middle Name/Initial' },
    { code: 'postcode', name: 'Zip/Postal Code' },
    { code: 'prefix', name: 'Prefix' },
    { code: 'region', name: 'State/Province' },
    { code: 'region_id', name: 'State/Province' },
    { code: 'street', name: 'Street Address' },
    { code: 'suffix', name: 'Suffix' },
    { code: 'telephone', name: 'Phone Number' },
    { code: 'vat_id', name: 'VAT number' },
    { code: 'vat_is_valid', name: 'VAT number validity' },
    { code: 'vat_request_date', name: 'VAT number validation request date' },
    { code: 'vat_request_id', name: 'VAT number validation request ID' },
    { code: 'vat_request_success', name: 'VAT number validation request success' }
  ],
  new: [
    { code: 'city', name: 'City' },
    { code: 'company', name: 'Company' },
    { code: 'country_id', name: 'Country' },
    { code: 'emarsys_test_building_type', name: 'Building Type' },
    { code: 'emarsys_test_door_bell', name: 'Door Bell' },
    { code: 'emarsys_test_floor', name: 'Floor' },
    { code: 'emarsys_test_type_of_residence', name: 'Type Of Residence' },
    { code: 'emarsys_test_type_of_street', name: 'Type Of Street' },
    { code: 'fax', name: 'Fax' },
    { code: 'firstname', name: 'First Name' },
    { code: 'lastname', name: 'Last Name' },
    { code: 'middlename', name: 'Middle Name/Initial' },
    { code: 'postcode', name: 'Zip/Postal Code' },
    { code: 'prefix', name: 'Name Prefix' },
    { code: 'region', name: 'State/Province' },
    { code: 'region_id', name: 'State/Province' },
    { code: 'street', name: 'Street Address' },
    { code: 'suffix', name: 'Name Suffix' },
    { code: 'telephone', name: 'Phone Number' },
    { code: 'vat_id', name: 'VAT Number' },
    { code: 'vat_is_valid', name: 'VAT number validity' },
    { code: 'vat_request_date', name: 'VAT number validation request date' },
    { code: 'vat_request_id', name: 'VAT number validation request ID' },
    { code: 'vat_request_success', name: 'VAT number validation request success' }
  ]
};

module.exports = {
  customerAttributes,
  customerAddressAttributes
};
