name: Run tests
on:
  push:
    branches:
      - master
  pull_request:
​
permissions:
  contents: read
​
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Run gitlab tests
        uses: digital-blueprint/gitlab-pipeline-trigger-action@main
        with:
          host: "${{ vars.GITLAB_URL }}"'
          trigger_token: ${{ secrets.DEPLOY_TRIGGER_TOKEN }}
          access_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          id: '227'
          ref: 'main'
          variables: '{"MAGENTO_EXTENSION_BRANCH": "${{ steps.extract_branch.outputs.branch }}"}'
          
