FROM emarsys/ems-integration-cypress:3.4.1
ARG NPM_TOKEN
ENV NPM_TOKEN=${NPM_TOKEN}

COPY test /test

WORKDIR /test
RUN npm i && \
    ./node_modules/.bin/cypress install && \
    ./node_modules/.bin/cypress verify
