FROM emarsys/ems-integration-cypress:3.6.1
ARG NPM_TOKEN
ENV NPM_TOKEN=${NPM_TOKEN}

COPY test /test
COPY README.md /test/README.md

WORKDIR /test
RUN npm i && \
    ./node_modules/.bin/cypress install && \
    ./node_modules/.bin/cypress verify


#CMD /usr/local/bin/shell.sh ; sleep infinity
