<?php
/**
 * @category   Emarsys
 * @package    Emartech_Emarsys
 * @copyright  Copyright (c) 2017 Emarsys. (http://www.emarsys.net/)
 */
/** @var \Emartech\Emarsys\Block\Snippets $block */
?>

<?php $mageData = $block->getTrackingData() ?>
<p>SKU: <?php echo $mageData['sku'] ?></p>
<p>Search Term: <?php echo $mageData['searchTerm'] ?></p>
<p>Category: <?php echo $mageData['category'] ?></p>
<p>Merchant ID: <?php echo $mageData['merchantId'] ?></p>
