<?php
/**
 * @category   Emarsys
 * @package    Emartech_Emarsys
 * @copyright  Copyright (c) 2017 Emarsys. (http://www.emarsys.net/)
 */
/** @var \Emartech\Emarsys\Block\Snippets $block */
?>
<script>
  require(['Magento_Customer/js/customer-data'], function (customerData) {
    window.x = customerData;
    customerData.get('customer').subscribe(function (value) {
      console.log('customer', value);
    });

    customerData.get('cart').subscribe(function (value) {
      console.log('cart', value);
    });

    customerData.get('order').subscribe(function (value) {
      console.log('order', value);
    });
  });
</script>

<p>SKU: <?php echo $block->getSku() ?></p>
<p>Search Term: <?php echo $block->getSearchTerm() ?></p>
<p>Category: <?php echo $block->getCategory() ?></p>
